# Generated by Django 5.1.11 on 2025-08-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reg_num', models.CharField(max_length=12, unique=True)),
                ('day', models.CharField(max_length=15)),
                ('stand', models.CharField(max_length=15)),
                ('seat', models.CharField(max_length=15)),
            ],
        ),
    ]
