# Generated by Django 5.1.11 on 2025-08-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='day',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stand',
            new_name='reg_counter',
        ),
        migrations.AddField(
            model_name='student',
            name='program_group',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='program_name',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='school_name',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(default='x', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_category',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
    ]
